name: qdrant Docker Creation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:

  build:
    runs-on: 
      labels: [self-hosted, x64]

    steps:
    - name: Set up secret file
      env:
        MY_SECRET: ${{ secrets.BC_API_KEY }}
      run:
        echo $MY_SECRET >> /home/mwireman/secrets.txt
    
    - name: Set Secret as variable
      run:
        export FAKE_USERNAME="fakename"
        export FAKE_PASSWORD="fakepassword123!"
        
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run Prisma Cloud 
      id: prisma-cloud
      uses: bridgecrewio/checkov-action@master
      env:
        PRISMA_API_URL: https://api.prismacloud.io
      with:
        api-key: ${{ secrets.BC_API_KEY }}
        
    - name: Create VectorGen Docker
      run: docker build -f dockerimages/vectordbgen_image -t vectordbimage:v1.0 .
